services:
  db:
    image: mysql:8.0
    container_name: motorsportpage_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    ports:
      - "3308:${MYSQLPORT}"
    volumes:
      #Al montar ./src/database en /docker-entrypoint-initdb.d, MySQL ejecuta automáticamente todos los archivos .sql en este directorio solo durante la primera inicialización (cuando la base de datos no existe).
      - ./src/database/db.init.sql:/docker-entrypoint-initdb.d/db.init.sql
    networks:
      - motorsportpage-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: motorsportpage_image
    container_name: motorsportpage_app
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    volumes:
      # Montar directorios para desarrollo: los cambios se reflejan automáticamente sin reconstruir
      - ./public/:/var/www/html/public
      - ./src/:/var/www/src
      # Montar vendor para que los cambios en dependencias se reflejen sin reconstruir
      - ./src/vendor/:/var/www/src/vendor
    env_file:
      - .env
    networks:
      - motorsportpage-net

networks:
  motorsportpage-net:
    driver: bridge
